# Generated by Django 4.2.4 on 2023-09-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
